#!/bin/sh
IFS='
'
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
destination="${file%.*}_X265.mkv"
ffmpeg -i $file -c:a copy -c:v libx265 -preset medium -crf 23  $destination
done
notify-send --urgency=low -i totem "Conversion Completed"
