#!/bin/sh
IFS='
'
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
destination="${file%.*}++.pdf"
ghostscript -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$destination $file
done
notify-send --urgency=low -i totem "Conversion Completed"
